spring:
#设定静态文件路径，js,css等
  mvc:
    static-path-pattern: /**
  datasource:
    url: jdbc:mysql://localhost:3306/ssh?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
#      dialect: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
#logging:
  ## com.keveon: trace
   # com.mysql: warn
   # org.hibernate: warn
   # org.springframework: warn

