spring:
  application:
    name: order-flow
  jackson:
    serialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/flow?zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: 123456
  jpa:
      show-sql: true
      format_sql: true
      generate-ddl: true
      properties:
        dialect: org.hibernate.dialect.MySQL5Dialect
  #      dialect: org.hibernate.dialect.Oracle10gDialect
      hibernate:
        ddl-auto: update
        naming:
          strategy: org.hibernate.cfg.ImprovedNamingStrategy
  kafka:
    bootstrap-servers: 172.16.13.217:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
    properties:
      request.timeout.ms: 200000 # 消息发送的最长等待时间.需大于session.timeout.ms这个时间
      session.timeout.ms: 120000 # 在session.timeout.ms这个时间内处理完
    listener:
      concurrency: 10
      poll-timeout: 1000
      ack-mode: batch
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      group-id: order-center
      auto-commit-interval: 5000
      fetch-max-wait: 120000
      max-poll-records: 10
server:
  tomcat:
    max-threads: 1000
    uri-encoding: UTF-8
  port: 8073
